### ISSUE TITLE
Is this OS a frontend "fake" OS, or a real kernel?

### ISSUE THREAD

**Issue by naclcaleb** [rocketbear27/cubeX#1]
I'm wondering whether this "miniOS" is a frontend "fake" OS - like [this](https://geekprank.com), for example, or if you are actually planning to make an actual kernel with assembly and C/C++.

I assume it's the former, but I just want to make it clear.

**Comment by rocketbear27** [comment]
Currently, I am doing what the link is doing. Hopefully, in the future, I will make an actual kernel. The problem is I have never learned assembly and c or c++, and I don't have the time to go learn.

**Comment by naclcaleb** [comment]
Nice! That means I can help more!

It actually doesn't take much assembly at all. I've created a kernel before, but I don't know much about assembly.

I'd say to start with C++.

I'd also recommend going through [this video series](https://www.youtube.com/channel/UCQdZltW7bh1ta-_nCH7LWYw).

Mind, it is a long and arduous process, and not very exciting for a while, but you learn a lot of important things.
